### ISSUE TITLE
Simplify code and use SafeMath as a library (not a contract)

### ISSUE THREAD

**Issue by pauliax** [EthereumCommonwealth/DexNS#10]
`if(safeSub(msg.value, namePrice ) > 0)`
could be refactored to 
`if(msg.value > namePrice )`
to avoid external call and subtraction operation. This will save some gas. Consider updating it in several places. 

Also, consider using SafeMath as a library, not a contract. This will also save a significant amount of gas. Now:
contract DexNS_Frontend is safeMath
Suggested: 
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/math/SafeMath.sol
using SafeMath for uint256;

**Comment by Dexaran** [comment]
Here is an example of computations (1) without safe math, (2) with safe math as contract and (3) safe math as library as you suggested:

1. `((a + b) / c) - d + a`

2. `safeAdd( safeSub( (safeAdd(a, b)/c), d ), a)`

3. `( a.add( b ) / c ).sub( d ).add( a )`

I'm not sure but the second approach seems to be more readable for me.

**Comment by pauliax** [comment]
@Dexaran This suggestion was not intended to improve the readability (I didn't mention it anywhere). It was supposed to reduce the gas consumption (gas costs money), as the library is cheaper than a contract.

**Comment by Dexaran** [comment]
Alright. In case of a single use `now.add(owningTime)` is readable enough. Let's stick with OpenZeppelin's suggested implementation of safeMath.
