### ISSUE TITLE
too many nested IFs

### ISSUE THREAD

**Issue by pauliax** [EthereumCommonwealth/DexNS#12]
Consider refactoring the code below:    
```
    if(!(msg.value < namePrice))
        {
           ... other code ...
        }
        revert();
```
to:
```
    require(msg.value >= namePrice);
           ... other code ...
```
to make the code more clean and readable.

There are several places where this approach is used.

**Comment by Dexaran** [comment]
I would say that 

```js

if(condition)
{
    ... some code ...
}
```

code is intuitively clear for any programmer, while 

```js

require(condition);
... some code ...
```

requires programmer to research about how `require` works in Ethereum and if it works the same in Ethereum and ETC. That's why I was staying with `IFs`.

**Comment by pauliax** [comment]
I could argue that 
```
require(condition1);
require(condition2);
require(condition2);
```

is not more clear than 
```
if(condition1)
{
     if(condition2) 
     {
         if(condition3)
         { 
             //do something
          }
      }
}
```

especially for those who have some experience in Solidity development. This approach is also highly applied in all the code of OpenZeppelin which provides standard smart contracts for everyone. Another point that I wanted to show was that this:
`!(msg.value < namePrice)`
by using "require" instead of "if" could be refactored to
`msg.value >= namePrice`
which I think is an obvious improvement for code's readability and will consume slightly less gas.
