### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by pauliax** [EthereumCommonwealth/DexNS#13]
if (db.addressOf("DexNS commission").send(namePrice))

It's generally advised to avoid hardcoded values in functions. Functions shouldn't have magic numbers inside it. It makes harder to maintain the code and also decreases readability. Imagine if you use a magic number, let's say 350 ten times in your code. One day you decide to change it from 350 to 360. What do you do? You search all occurrences in the code and change them. If you have this value extracted, you can change it only in one place to achieve the same effect.

In DexNS_Frontend the hardcoded value "DexNS commission" is used 4 times, so it would be a good practice to extract it to a const variable:
string private const DEXNSComission = "DexNS commission";
the good thing is that it doesn't cost gas to read from a const variable, so it will also save you some gas.

Also, a value of 32 is used in many places, so consider extracting it also.

**Comment by Dexaran** [comment]
Confirmed. Fixed with https://github.com/EthereumCommonwealth/DexNS/commit/c6d8c031408ffa97f1962ee6849f6b7d923cc8e3

**Comment by Dexaran** [comment]
This bug was evaluated as point 2 of the bug bounty: **code flaws that can not violate contract workflow and code improvements**.

I'm ready to reward you for issues #13 , #10 and #8 with $250 in ETC or any other crypto that I can buy if you don't like ETC. Please, provide your address here.

**Comment by pauliax** [comment]
Thank you. My ETC (Ethereum Classic) address: **0x6b9CB0B5D99Fc1232611014f15db2Cf17F8D7F81**

**Comment by Dexaran** [comment]
The reward will be evaluated at Nov 30, 2017 23:00 CEST by Poloniex ETCUSDT rate and then I will send it to `0x6b9CB0B5D99Fc1232611014f15db2Cf17F8D7F81` address.

**Comment by Dexaran** [comment]
Sent: https://gastracker.io/tx/0x8b8e9dac1bc52184c71f4c2cb7aff833f8ba7bfce0a2a327a112d4af4dfe1286
