### ISSUE TITLE
Use A>=B instead of !(A<B)

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#14]
For example
https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol#L144
could be changed to:
`if(msg.value >= namePrice)`

**Comment by Dexaran** [comment]
This makes no sense and does not change the logic or save any gas.

**Comment by io4** [comment]
A comparison and then a negation has a higher gas cost than just one comparison.
