### ISSUE TITLE
registerName docs say that it returns false on failure but instead throws

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#15]
At https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol#L176

**Comment by Dexaran** [comment]
>@return ok    True on successful Name registration, false in any other cases.

`false` in any unexpected circumstances. Normally, function will return `true` or fail at all.

**Comment by io4** [comment]
There is no possible situation where it would return false. The docs should include "throws otherwise"

**Comment by Dexaran** [comment]
Imagine that a user has called something else (not current DexNS frontend contract) and it will not return `true`. In this case it will be easier to detect an error that occurs with execution of a wrong contract.

**Comment by io4** [comment]
You could include that the function throws to the docs, while keeping the true on success and false on fail part.
