### ISSUE TITLE
Debug mode cannot be re-enabled

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#17]
Debug mode can not be set to true, so once disabled, name price and ownership time cant be modified, and stuck tokens cant be released.

**Comment by Dexaran** [comment]
This works exactly as expected.

Debug mode can only be disabled, making the contract system immutable (frontend and storage contracts could not be re-deployed after the disable of debug mode). Name price depends on ETCUSD rateo so it can not be an immutable option.
