### ISSUE TITLE
You can make comission's name expire (in a year, instead of infinite) by extending the date

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#20]
If you call extend_Name_Binding_Time() with DexNS comission's name you can reduce its expire date from a date far in the future (999999999999) to in a year.

Line of code: https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol#L349

**Comment by Dexaran** [comment]
I would say that "DexNS commission" is one of the DexNS names and it should behave as any of the DexNS names. In this case, it is a normal behavior.

**Comment by io4** [comment]
But the first code intends to set some very high number, which seems to have the intention to avoid the name from expiring, as its the hardcoded address where all payments are sent.
If nobody notices that someone reduced the time (assuming we will never get to timestamp 99999999999 soon), the name would expire.

**Comment by Dexaran** [comment]
I tend to agree that you can make DexNS commission expire as any other name, but this can not affect the workflow of the contract or make any harm. BTW, it is necessary to allow someone else to claim the ownership of DexNS if the owner will not be confirming that he is still alive from time to time.

 This can not be evaluated as bug, security vulnerability or code flaw.
