### ISSUE TITLE
Funds can get locked in DexNS_Frontend

### ISSUE THREAD

**Issue by NickErrant** [EthereumCommonwealth/DexNS#21]
if `db.addressOf(DexNSCommission).send(namePrice)` fails, the funds sent as payment will be locked in `DexNS_Frontend` as there is no way to retrieve funds from the contract (after debug is disabled).
In the cases of `registerAndUpdateName()` & `registerName()` this means the registration is completed but the funds will be stuck & the `NameRegistered()` event won't be emitted, and an overpaying user won't receive their change.
In the case of `extend_Name_Binding_Time()` the funds will be stuck, and the user will not receive their payed for extension-- not to mention any ether they overpaid.

Fix:
`db.addressOf(DexNSCommission).transfer(namePrice)` will throw on fail, and ensure funds do not get stuck. If this fix isn't amenable to you, at the least, adding a method for retrieving the balance of the contract would be prudent.

**Comment by Dexaran** [comment]
The purpose of this approach is to ensure that the workflow of the contract is not interrupted in the event of an unsuccessful attempt to send money to `DexNS commission`.

If the DexNSCommission fails to receive the funds, then we should manually refund a user with a [debugCall](https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol#L437-L444).

The key issue here is that we should be sure that DexNSCommission will not fail to receive funds at the moment of debug disabling.

We can not rely on `.transfer` because it will interrupt the whole transaction and user will be unable to register a name if DexNSCommission fails to accept funds (which is not the user's fault).

**Comment by NickErrant** [comment]
Then you should move [this line](https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol#L349) above [that line](https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol#L347) so if the DexNSCommission fails to receive the funds users can still extend their domain expiration.

Also is `disable_Debug()` intended to be called during normal operation of the contract? B/c the reported issue of funds getting locked is dependent on debug being disabled: 

>  there is no way to retrieve funds from the contract (after debug is disabled).

**Comment by Dexaran** [comment]
Contract should be deployed in the debug mode. Then it will work for some time (say 5 years) and if no bugs would be discovered during this process then we can disable the debug mode. 

Parity multisig was hacked twice, but it works for months. As the result, we need to keep the debug mode turned on long enough.

**Comment by NickErrant** [comment]
> Then you should move this line above that line so if the DexNSCommission fails to receive the funds users can still extend their domain expiration.

Still stands.

As to debug mode, the address mapped to "DexNS commission" could change at any time (e.g. after debug is disabled), so the risk of transfers failing is always there, no?

**Comment by NickErrant** [comment]
Furthermore, is there any reason sending overpayed Ether back is conditional on DexNSCommission successfully receiving its fees?

You can use send instead of transfer, and still address the above issues by:

1. removing the `if (db.addressOf(DexNSCommission).send(namePrice))` statements, & replacing them with sends that you don't check the return value of
2. adding a method with `only_owner` modifier but not `only_debug` to the effect of `owner.transfer(this.balance)`
