### ISSUE TITLE
Keeping Expiration Dates in Frontend Complicates Migration

### ISSUE THREAD

**Issue by janbro** [EthereumCommonwealth/DexNS#22]
https://github.com/EthereumCommonwealth/DexNS/blob/6700de1e6e85d75a74d7c840c01b4a7c0cfc06bb/DexNS_Frontend.sol#L106

The expiration date map for names is stored in the front end contract. Since the storage contract has a way to change the front end contracts address, I assume the front end is something that has the potential to be updated, which would in turn reset the expiration date stored for every name. Potential fix is to move the expiration to be a state variable in the storage contract.

**Comment by Dexaran** [comment]
Name expiration and registration logic is not a part of DexNS storage contract. It only belongs to frontend contract. In case of frontend contract upgrade we can just implement a check like this:

```js

    function registerName(string _name) payable returns (bool ok)
    {
        if(expitations[_name] < now && prev_frontend_address.expirations[_name] < now) {
            // register a name.
        }
        else {
            revert();
        }
    }
```

**Comment by Dexaran** [comment]
Time-based names expiration logic is not a core part of DexNS to be honest. It could be replaced with something else in future. As the result, there is no reason to keep an expiration date at the storage contract.
