### ISSUE TITLE
transaction failing: 0xc377a72648 registration

### ISSUE THREAD

**Issue by nimbosa** [EthereumCommonwealth/DexNS#23]
`registerName` function fails for registration under address: [0xfFd7eb7254](http://gastracker.io/addr/0xffd7eb72549c7a07cea9f4b88ca05abc078e4f48) on Ethereum Classic

Transaction Details here: [0xc377a72648](https://gastracker.io/tx/0xc377a7264867abff9566594bcb727920de54f557b782ccf9613828535c2236ee)

why?

**Comment by Dexaran** [comment]
DexNS require 0.1 ETC fee to be sent with the transaction. It is a one time payment for the name registration to prevent name spamming.
