### ISSUE TITLE
sha256 is refferenced as keccak256

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#3]
In https://github.com/EthereumCommonwealth/DexNS/blob/687ca9359f06fcadc604bb7ecc1622076a815657/DexNS_Storage.sol#L54-L62 the comment says that it "Returns keccak-256 hash of the Name." but instead it performs sha256.

**Comment by Dexaran** [comment]
Confirmed. Comment mistake.

**Comment by Dexaran** [comment]
This bug was evaluated as point 2 of the bug bounty: **code flaws that can not violate contract workflow and code improvements**.

I'm ready to reward you with $100 in ETC or any other crypto that I can buy if you don't like ETC. Please, provide your address here.

**Comment by io4** [comment]
I prefer ETH (if not possible I am fine with ETC), and my address is 0x9FCfE63108f0957aAD1C6F2eD30270e8D35C6491

**Comment by Dexaran** [comment]
Sent: https://gastracker.io/tx/0x94f93ebe77ec0dc5a70e55534aaad832784646aac24ede8cf9099bedcfea4e5c
