### ISSUE TITLE
keccak256 hash is refferenced as a "signature" while its just a checksum/hash/digest

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#4]
In https://github.com/EthereumCommonwealth/DexNS/blob/687ca9359f06fcadc604bb7ecc1622076a815657/DexNS_Storage.sol#L178-L189 the function signatureOf uses keccak256 which is not related with signatures (which involves signing using a private key, the message might be first hashed)

**Comment by Dexaran** [comment]
A signature of the Name is its hash. This function works exactly as expected.

**Comment by io4** [comment]
I just meant that signature is not a correct term for hashing, not that the function did not work.
