### ISSUE TITLE
Duplicated function updateName, which run different code

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#5]
In https://github.com/EthereumCommonwealth/DexNS/blob/687ca9359f06fcadc604bb7ecc1622076a815657/DexNS_Frontend.sol#L211-L255

**Comment by Dexaran** [comment]
Different `updateName` functions allow to update:
1. Only address of the Name.
2. Only metadata of the Name.
3. Both address and metadata of the Name.

It is possible that a user will look for opportunity to update one of them without affecting an another.
