### ISSUE TITLE
What is the purpose of name hiding?

### ISSUE THREAD

**Issue by io4** [EthereumCommonwealth/DexNS#6]
If it is to hide the owner from everyone, then the data of name ownership can still be found by looking at older blocks or at the transaction to hide.

**Comment by Dexaran** [comment]
The main purpose of `hideOwner` is to disallow other contracts to access `ownerOf` directly. `addressOf` should always be accessed from other contracts. It is possible that addressOf and ownerOf will point to different addresses. In this case it's better to `throw` than to have funds sent to a wrong address.
