### ISSUE TITLE
Send() is deprecated

### ISSUE THREAD

**Issue by pauliax** [EthereumCommonwealth/DexNS#7]
db.addressOf("DexNS commission").send(namePrice)
Please avoid "send" in Solidity, as there is a better alternative that is more secure. “send" does not throw an exception when not successful. Use "transfer" whenever failure of the ether transfer should rollback the whole transaction.
There are several usages of "send" in your contract.

**Comment by Dexaran** [comment]
I'm aware of the specifics of `.send` functionality of Solidity. It does not throw on failure, but returns a `false` value. It requires `.send` return value to be properly handled and I suppose that it is currently implemented in DexNS frontend contract.
